### ISSUE TITLE
json-cycle 197,671 Operations / second (not 197.671)

### ISSUE THREAD

**Issue by i6ma** [planttheidea/fast-stringify#1]
[Simple objects](https://github.com/planttheidea/fast-stringify/blob/master/README.md#simple-objects) of Benchmarks,

json-cycle | 197.671 (Operations / second)
should be 197,671 at [README.md#L58](https://github.com/planttheidea/fast-stringify/blame/master/README.md#L58)

**Comment by planttheidea** [comment]
Thanks for the heads up! Fixed. :)
