### ISSUE TITLE
no circular but the same reference

### ISSUE THREAD

**Issue by i6ma** [planttheidea/fast-stringify#2]
less often than circular objects, but not never
just like:
```javascript
import stringify from "fast-stringify";

const foo = {};

const object = {
  bar: foo,
  baz: foo,
  qux: foo
};

console.log(stringify(object));       // {"bar":{},"baz":"[ref-0]","qux":"[ref-1]"}
console.log(JSON.stringify(object));  // {"bar":{},"baz":{},"qux":{}}
```

**Comment by planttheidea** [comment]
Thanks for the heads up here! Looks like my original setup was too basic, but I've just released `1.0.1` which should prevent this issue from occurring. If there are any more issues, let me know!
