### ISSUE TITLE
not exactly, both circular and recur

### ISSUE THREAD

**Issue by i6ma** [planttheidea/fast-stringify#5]
I am puzzled by this for times, want to really make a PR, but no pithy idea.
It's a wise idea to cache the value with the replacer, beyond all my expectations.
I have read the createReplacer, there still a flaw like this:

```javascript
import stringify from "fast-stringify";

const foo = {bar: []};

const object = {
  foo: foo,
  bar: foo,
  baz: {},
};

object.baz.foo = object.foo;    // {"foo":{"bar":[]},"bar":"[ref-0]","baz":{"foo":"[ref-1]"}}
// object.baz.baz = object.baz; // TypeError: Converting circular structure to JSON

console.log(stringify(object));
```

**Comment by planttheidea** [comment]
Yup ... alright I think the experiment of the `WeakSet` as cache is a no-go, because it doesn't let me "reset" the values other than the one being processed. I think I may have found a way to make the use of an `Array` cache as performant, and it will give me more flexibility to prevent false positives ... let me tinker, I should have something soon.

**Comment by planttheidea** [comment]
Ok I think I've got it ... I tried both examples you provided (the one with false positives, as well as the one creating circular references) and they stringify as expected. I originally went with `WeakSet` for performance reasons, but I was able to do some tweaks with a more standard `Array` cache that made comparable in performance to the previous iteration (while obviously being more accurate). The fix should be available in `1.0.3`.

Thanks for the report! If you have any other issues, please let me know. :smile_cat:

**Comment by i6ma** [comment]
about [function first](https://github.com/planttheidea/fast-stringify/blob/master/src/utils.js#L11)
> get the first n number of items from the array as a new array (faster than native splice)

how about ```return array.slice(0, length);``` here is ```slice```, not ```splice```.

maybe this also work: ```array.length = length;```
if we dont want a new array, but just want to remove items of the tail.

**Comment by planttheidea** [comment]
The reason for this is speed... I did perf testing and to my surprise, the new array was fastest!

FYI, slice creates a new array as well. To mutate, you want splice.
